# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
	# check these on https://fabricmc.net/develop
	minecraft_version=1.21
	yarn_mappings=1.21+build.2
	loader_version=0.15.11

# Mod Properties
	mod_version = 2.0-alpha.1+1.21
	maven_group = qu
	archives_base_name = qu-enchantments

# Dependencies
	fabric_version=0.100.4+1.21
	mixin_extras_version = 0.3.6